global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'yichen-grpc-service-monitor'
 
scrape_configs:
#  - job_name: grpcserver
#    static_configs:
#      - targets: ['localhost:9090']
#        labels:
#          instance: prometheus
#
  - job_name: grpcserver
    scrape_interval: 3s
    static_configs:
      - targets: ['awesome-service-container:9092']
        labels:
          instance: docker
