# GO CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          - GOCACHE: "/tmp/go/cache"
          - DEP_VERSION: 0.5.4

    working_directory: /go/src/grpc-gw-test

    steps:
      - checkout

      - restore_cache:
            key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
            paths:
              - /go/src/grpc-gw-test/vendor

      - run:
          name: Download packages
          command: |
            dep ensure

      - save_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/src/grpc-gw-test/vendor

      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
          paths:
            - /tmp/go/cache

      - run:
          name: Static check
          command: go vet -v ./...

      - run:
          name: Unit test
          command: go test -cover -v ./...

      - run:
          name: Benchmark
          command: go test -bench=".*"

