# GO CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
#
version: 2
jobs:
  build:
    docker:
      #      - image: golang:alpine
      - image: circleci/golang:1.12
        environment:
          - GOCACHE: "/tmp/go/cache"
          - DEP_VERSION: 0.5.4

    working_directory: /go/src/github.com/kinddevil/grpc-gw-test

    steps:
      - checkout
      #      - restore_cache:
      #            key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
      #            paths:
      #              - /go/src/github.com/kinddevil/grpc-gw-test/vendor
      - run:
          name: Download packages
          command: |
            dep ensure
      #      - save_cache:
      #          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
      #          paths:
      #            - /go/src/github.com/kinddevil/grpc-gw-test/vendor
      #      - restore_cache:
      #          keys:
      #            - build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
      #          paths:
      #            - /tmp/go/cache
      - run:
          name: Hack working dir
          command: |
            echo default working dir $PWD
            echo gopath - $GOPATH
            mv $GOPATH/src/github.com/kinddevil/grpc-gw-test $GOPATH/src/

      - run:
          name: Unit test
          command: go test -v ./...

#      - restore_cache: # restores saved cache if no changes are detected since last run
#          keys:
#            - go-mod-v4-{{ checksum "go.sum" }}
#
#      - save_cache:
#          key: go-mod-v4-{{ checksum "go.sum" }}
#          paths:
#            - "/go/pkg/mod"
